allowBuilds:
  koffi: true
overrides:
  '@deepseek-ai/dsh-llm': file:tarballs/deepseek-ai-dsh-llm-0.1.6-alpha.2.tgz
  '@deepseek-ai/dsh-attachment': file:tarballs/deepseek-ai-dsh-attachment-0.1.6-alpha.2.tgz
  '@deepseek-ai/dsh-fs': file:tarballs/deepseek-ai-dsh-fs-0.1.6-alpha.2.tgz
  '@deepseek-ai/dsh-execution-world-affinity': file:tarballs/deepseek-ai-dsh-execution-world-affinity-0.1.6-alpha.2.tgz
